# Generated by Django 3.1.3 on 2021-01-28 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='demo', max_length=20)),
                ('user_password', models.CharField(default='demo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Post_Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(default='Add Please', upload_to='blog_images')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog_App.blog_user')),
            ],
        ),
    ]
