# Generated by Django 3.1.3 on 2021-01-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0002_post_blog_blog_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(default='demo', max_length=100)),
                ('name', models.CharField(default='demo', max_length=20)),
                ('comment', models.CharField(default='demo', max_length=100)),
            ],
        ),
    ]
